version: '2'

services:
    # =-=-=-=-= GOLANG =-=-=-=-=
    golang:
      build:
        context: .
        dockerfile: Dockerfile.dev
      container_name: LWAGolang_dev
      ports:
        - "3000:3000"
      volumes:
        - .:/go/src/github.com/lovohh/lovohhwebapi/
      environment:
        - LWA_EMAIL_UN=$EMAIL_UN
        - LWA_EMAIL_PW=$EMAIL_PASS
